import numpy as np

# Cargar el archivo .npy
dat = np.load("/mnt/c/Users/vicen/Documents/GitHub/Vision3D/Etapa1/data/P.npy")
data = np.load("/mnt/c/Users/vicen/Documents/GitHub/Vision3D/Etapa2/data/K_intrinseca.npy")
data2 = np.load("/mnt/c/Users/vicen/Documents/GitHub/Vision3D/Etapa2/data/R_rotacion.npy")
data3 = np.load("/mnt/c/Users/vicen/Documents/GitHub/Vision3D/Etapa2/data/t_traslacion.npy")
data4 = np.load("/mnt/c/Users/vicen/Documents/GitHub/Vision3D/Etapa3/data/F.npy")
data5 = np.load("/mnt/c/Users/vicen/Documents/GitHub/Vision3D/Etapa3/data/inliers.npy")
data6 = np.load("/mnt/c/Users/vicen/Documents/GitHub/Vision3D/Etapa3/data/pts1.npy")
data7 = np.load("/mnt/c/Users/vicen/Documents/GitHub/Vision3D/Etapa3/data/pts2.npy")
data8 = np.load("/mnt/c/Users/vicen/Documents/GitHub/Vision3D/Etapa4/data/E.npy")
data9 = np.load("/mnt/c/Users/vicen/Documents/GitHub/Vision3D/Etapa5_6/data/Hl.npy")
data10 = np.load("/mnt/c/Users/vicen/Documents/GitHub/Vision3D/Etapa5_6/data/Hr.npy")
data11 = np.load("/mnt/c/Users/vicen/Documents/GitHub/Vision3D/Etapa5_6/data/R_rectified.npy")
data12 = np.load("/mnt/c/Users/vicen/Documents/GitHub/Vision3D/Etapa5_6/data/t_rectified.npy")

# Mostrar el contenido
print("Etapa 1: \n", dat)
print("\n")
print("Etapa 2: \n", data)
print("\n")
print("Etapa 2: \n", data2)
print("\n")
print("Etapa 2: \n", data3)
print("\n")
print("Etapa 3: \n", data4)
print("\n")
print("Etapa 3: \n", data5)
print("\n")
print("Etapa 3: \n", data6)
print("\n")
print("Etapa 3: \n", data7)
print("\n")
print("Etapa 4: \n", data8)
print("\n")
print("Etapa 5-6: \n",data9)
print("\n")
print("Etapa 5-6: \n",data10)
print("\n")
print("Etapa 5-6: \n",data11)
print("\n")
print("Etapa 5-6: \n",data12)

